# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsHubRss' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsHubRss
  pod 'SwiftSoup', :inhibit_warnings => true
  pod 'FeedKit'
  pod 'SwiftLint'

  target 'NewsHubRssTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsHubRssUITests' do
    # Pods for testing
  end

end
